apiVersion: apps/v1
kind: Deployement
metadata:
   name: clahan-deployment
   labels:
      name: webapp
spec:
 replicas: 2
 selector:
    matchLabels:
      name: webapp
 template:
    metadata:
      name: clahan-pod
      labels:
        name: webapp
    spec:
     containers:
     - name: clahan-container
       image: raghav195/clahan-product
       ports:
       - containerPort: 80

   